In [1]:
import pandas as pd

In [2]:
review_df = pd.read_csv('output/reviews_scores.csv')

In [4]:
review_df.head()

,id,roberta_neg,roberta_neu,roberta_pos,output,restaurant_ids,id_review,caption,relative_date,username,name,cuisine
0,0,0.005796,0.054793,0.939411,positive,1,ChdDSUhNMG9nS0VJQ0FnSURSOTRpbmxnRRAB,Great experience,6 days ago,Sandeep Kaur,Domino's Pizza Flinders St,Fast Food
1,1,0.984013,0.013361,0.002626,negative,1,ChdDSUhNMG9nS0VJQ0FnSURScktPaDV3RRAB,Must be the worst dominos in the world. Pizz...,3 weeks ago,Robert McFarland,Domino's Pizza Flinders St,Fast Food
2,2,0.002001,0.007393,0.990606,positive,1,ChZDSUhNMG9nS0VJQ0FnSURSNUotOUt3EAE,They are so nice and the Food is Perfect !!,3 weeks ago,Patricia Tchialeu,Domino's Pizza Flinders St,Fast Food
3,3,0.003910,0.041748,0.954342,positive,1,ChdDSUhNMG9nS0VJQ0FnSURSNklYTG93RRAB,Staff was friendly and helpful. The deals make...,3 weeks ago,Brent Folan,Domino's Pizza Flinders St,Fast Food
4,4,0.003776,0.144302,0.851922,positive,1,ChZDSUhNMG9nS0VJQ0FnSUNPNXJhd0VREAE,Been coming here for awhile usually happy,a month ago,Johnathan Vanderwerf,Domino's Pizza Flinders St,Fast Food

In [18]:

grouped = review_df.groupby(['restaurant_ids', 'name', 'cuisine']).size().reset_index(name='count')

# Pivot the table to have one row per restaurant and output counts as columns
review_agg_df = grouped.pivot_table(index=['restaurant_ids', 'name', 'cuisine'], values='count', fill_value=0).reset_index()

# Calculate total reviews per restaurant
review_agg_df['total'] = review_agg_df['positive'] + review_agg_df['negative'] + review_agg_df['neutral']

# Calculate percentages
review_agg_df['positive_percentage'] = review_agg_df['positive'] / review_agg_df['total'] * 100
review_agg_df['negative_percentage'] = review_agg_df['negative'] / review_agg_df['total'] * 100
review_agg_df['neutral_percentage'] = review_agg_df['neutral'] / review_agg_df['total'] * 100

# Rename columns for better readability
review_agg_df.rename(columns={'positive': 'positive_count', 'negative': 'negative_count', 'neutral': 'neutral_count'}, inplace=True)

# Remove the 'total' column as it is not needed in the final output
# review_agg_df.drop(columns=['output'], inplace=True)

review_agg_df.head()

KeyError: 'positive'

In [15]:
review_agg_df.head()

output,restaurant_ids,name,cuisine,negative_count,neutral_count,positive_count,total,positive_percentage,negative_percentage,neutral_percentage
0,1,Domino's Pizza Flinders St,Fast Food,2,2,10,14,71.428571,14.285714,14.285714
1,2,City Kebabs,Fast Food,7,2,7,16,43.750000,43.750000,12.500000
2,3,Royale PizzaMelbourne,Pizza,10,1,15,26,57.692308,38.461538,3.846154
3,4,Cherry and Twigs,Café,2,1,20,23,86.956522,8.695652,4.347826
4,5,Restaurant 1903,Modern Australian,1,3,22,26,84.615385,3.846154,11.538462

In [14]:
review_agg_df.columns

Index(['restaurant_ids', 'name', 'cuisine', 'negative_count', 'neutral_count',
       'positive_count', 'total', 'positive_percentage', 'negative_percentage',
       'neutral_percentage'],
      dtype='object', name='output')